version: "3.3" # https://docs.docker.com/compose/compose-file/

services:
  tstapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - SERVER_PORT=80
    ports:
      - 80
    depends_on:
      - redis
    command: pipenv run python server.py

  redis:
    image: 'redis:5-alpine'
    command: redis-server --requirepass qwerty
    restart: always
    volumes:
      - data:/data

  nginx:
    image: nginx:latest
    volumes:
      - ./lb/conf.d:/etc/nginx/conf.d
    depends_on:
      - tstapp
    ports:
      - "8080:8080"

volumes:
  data:
  